# Site
repository: tuqpham0/tuqpham0.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Tuyen Pham
title: PhD student at the University of Florida
email: {first}.{last}@ufl.edu
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://tuqpham0.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
github_username:  tuqpham0
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: tuqpham
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0001-7379-4057
googlescholar_username: PbaipGsAAAAJ

# Additional icon links
additional_links:
- title: My UFL Page
  icon: My University page (https://fontawesome.com/icons/brain?f=classic&s=solid)
  url: (https://people.clas.ufl.edu/tuyen-pham/)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
# about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Tuyen Pham, I am a currently a graduate student at the University of Florida studying mathematics. I am currently looking for work in software engineering in general, but I have interest in machine learning, computer vision, and data science.
    - Lists
    - Tables
    - <a href="google.com">Links</a>
    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Bregman Kd-Trees
        icon: fab fa-github
        link: (tuqpham0.github.io/BANN)
        link_text: Bregman Approximate Nearest Neighbours
        additional_links:
          # - title:  Github page for Kd-trees extended to Bregman geometries
            # url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          While they are often asymmetric and never satisfy the triangle inequality, Bregman divergences (often used in machine learning) emit a suprisingly well-behaved geometry. In particular, a subfamily interacts surprisingly well with Kd-trees.
        description: | # this will include new lines to allow paragraphs
          This project is in collaboration with Dr. Hubert Wagner at the University of Florida. It is build from the ANN by Arya and Mount.
          
          It is built to quickly compute (approximate) $k$-nearest neighbours in the Bregman setting and to quickly compute the Bregman--Hausdorff divergence for decomposable Bregman divergences.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: PhD in Mathematics
        sub_title: University of Florida
        caption: 2021 -- 2026
        description: |
          Studied computational topology and geometry under Dr. Hubert Wagner. My research is in the topological and geometric analysis of neural networks and other machine learning models. I will receive my degree in May 2026.
            Dissertation: "Efficient tools for the geometric and topological analysis of machine learning models"

          You can find my list of presentations and publications at 
        title: MS Mathematics; BS Mathematics, Minor Statistics
        sub_title: Cal Poly
        caption: 2018 -- 2020; 2011 -- 2016
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Masters: studied pure mathematics and taught precalculus and calculus courses. For more information about my taught courses, see my CV.
            Thesis: "Topological Data Analysis" - An introductory survey on the mathematics behind TDA, mainly persistent homology, and an application to time series analysis.
            
          Undergraduate: studied applied mathematics with a focus on computer science and statistics.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Other Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
