# Site
repository: https://github.com/tuqpham0/tuqpham0.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Tuyen Pham
title: PhD student in mathematics at the University of Florida
email: "{first}.{last}@ufl.edu"
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: tuqpham0.github.io
website_title: Portfolio and research

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: tuqpham
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0001-7379-4057
googlescholar_username: PbaipGsAAAAJ

# Additional icon links
additional_links:
- title: University of Florida page
  icon: fas fa-university
  url: https://people.clas.ufl.edu/tuyen-pham/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I am a PhD student in mathematics at the University of Florida. My research focuses on computational topology and geometry, with applications to machine learning.
  My current project focuses on creating efficient algorithms and data structures for working with Bregman divergences, a family of dissimilarity measures used in machine learning and data analysis, and their induced geometries.

  I have also worked on projects in computational topology, including an algorithm for computing generators of persistent homology.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Bregman Kd-trees
        link: tuqpham0.github.io/BANN
        link_text: BANN Package
        additional_links:
          - title: GitHub Repository for BANN
            icon: fab fa-github
            url: tuqpham0.github.com/BANN
          - title:  PyPI page for BANN
            icon: fab fa-python
            url: https://pypi.org/project/BANN/
        quote: >
          An efficient tool for computing (approximate) nearest neighbors with decomposable Bregman divergences. It also permits efficient algorithms for computing the Bregman--Hausdorff divergence.
        description: | # this will include new lines to allow paragraphs
          An extension of the kd-tree data structures for decomposable Bregman divergences. Despite often being assymmetric and never satisfy the triangle inequality, Bregman geometries admit a well-behaved geometry. This allows us to extend the Kd-tree beyond metric spaces and develop efficient algorithms.
          
          This work is done in collaboration with Dr. Hubert Wagner, and built off of the ANN package made by Arya and Mount.
  - title: Education
    layout: list
    content:
      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: PhD in mathematics
        sub_title: University of Florida
        caption: 2021 -- 2026
        # quote: >
        #    " "
        description: | # this will include new lines to allow paragraphs
          Studied computational topology and geometry under the supervision of Dr. Hubert Wagner. My research focuses on the topological and geometric analysis of machine learning models via their outputs or internal representations.

          - Dissertation: "Efficient tools for the Geometric and Topological Analysis of Machine Learning Models"
      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: MS in mathematics
        sub_title: CalPoly, San Luis Obispo
        caption: 2018 -- 2020
        # quote: >
        #   " "
        description: | # this will include new lines to allow paragraphs
          Studied pure mathematics and taught precalculus and calculus courses as a graduate teaching assistant. Graduated with honors.
          
          My master's thesis focused on the theory behind topological data analysis, in particular persistent homology, and explored its applications to time series analysis.
      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: BS in mathematics and Minor in statistics
        sub_title: CalPoly, San Luis Obispo
        caption: 2011 -- 2016
        # quote: >
        #   " "
        description: | # this will include new lines to allow paragraphs
          Studied applied mathematics with a focus on computer science, with a minor in statistics.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: SLO Classical Academy
        sub_title: Algebra I teacher
        caption: 2020 -- 2021
        link: https://sloclassical.org/
        # quote: >
        #   " "
        description: | # this will include new lines to allow paragraphs
          Taught Algebra I to high school and middle school students at a small private school in San Luis Obispo, CA.

          Was a member of a curriculum development team to adjust the curriculum to have better gradual flow of concepts and ease the introduction to higher degree polynomials.
  - title: Research interests
    layout: text
    content: | # this will include new lines to allow paragraphs
  - title: More about me
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
