# Site
repository: https://github.com/tuqpham0/tuqpham0.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Tuyen Pham
title: PhD student in mathematics at the University of Florida
email: "{first}.{last}@ufl.edu"
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://tuqpham0.github.io
website_title: Portfolio and Research
# publications: /research/
# publications_title: Publications

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: tuqpham
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
orcid_username: 0000-0001-7379-4057
googlescholar_username: PbaipGsAAAAJ

# Additional icon links
additional_links:
- title: Research overview
  icon: fas fa-university
  # url: https://people.clas.ufl.edu/tuyen-pham/research/
  url: https://tuqpham0.github.io/research/
- title: Resume
  icon: fas fa-briefcase
  url: https://tuqpham0.github.io/assets/Tuyen_Pham_-_Resume.pdf
- title: Curriculum Vitae
  icon: fas fa-graduation-cap
  url: https://tuqpham0.github.io/assets/Tuyen_Pham_-_CV.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/IMG_1206.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD student in mathematics at the University of Florida. My research focuses on computational topology and geometry, with applications to machine learning.
  My current project focuses on creating efficient algorithms and data structures for working with Bregman divergences, a family of dissimilarity measures used in machine learning and data analysis, and their induced geometries.

  My previous project was in computational topology: designing an algorithm for more efficiently computing generators of persistent homology.

  I am currently looking to transition into industry after graduation, and am interested in roles in data science, machine learning, and software engineering. You can find more about my qualifications in my [resume](https://tuqpham0.github.io/assets/Tuyen_Pham_-_Resume.pdf).

  I have previously taught Algebra I for high school and middle school students, and taught and TA'd many college math courses. For a detailed list, please see my [CV](https://tuqpham0.github.io/assets/Tuyen_Pham_-_CV.pdf).

  <div style="text-align: right; font-size: 2rem; font-weight: 500; margin-bottom: 0.25rem;">Research interests</div>
  My primary interests lie in computational topology and geometry, information geometry, data science, and machine learning. I am also interested in computer vision, animation, information theory and category theory.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
        #               # other value (or no value) means no border will be displayed
        title: Bregman Kd-trees
        link: https://github.com/tuqpham0/BANN
        link_text: BANN Package
        additional_links:
          - title: GitHub Repository for BANN
            icon: fab fa-github
            url: https://github.com/tuqpham0/BANN
          - title:  PyPI page for BANN
            icon: fab fa-python
            url: https://pypi.org/project/BANN/
        quote: >
          An efficient extention of Kd-trees to a non-metric setting often used in machine learning.
        description: | # this will include new lines to allow paragraphs
          An extension of the kd-tree data structures for decomposable Bregman divergences. Despite often being assymmetric and never satisfy the triangle inequality, Bregman geometries admit a well-behaved geometry. This allows us to extend the Kd-tree beyond metric spaces and develop efficient algorithms.
          
          This project is in collaboration with Dr. Hubert Wagner, and built off of the ANN package made by Arya and Mount.
  - title: Education
    layout: list
    content:
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: PhD in mathematics
        sub_title: University of Florida
        caption: 2021 -- 2026
        # quote: >
        #    " "
        description: | # this will include new lines to allow paragraphs
          Studied computational topology and geometry under the supervision of Dr. Hubert Wagner. My research focuses on the topological and geometric analysis of machine learning models via their outputs or internal representations.

          - Dissertation: "Efficient tools for the Geometric and Topological Analysis of Machine Learning Models"
      - layout: top-left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: MS in mathematics
        sub_title: Cal Poly, San Luis Obispo
        caption: 2018 — 2020
        # quote: >
        #   " "
        description: | # this will include new lines to allow paragraphs
          Studied pure mathematics and taught precalculus and calculus courses as a graduate teaching assistant. Graduated with honors.
          
          My master's thesis focused on the theory behind topological data analysis, in particular persistent homology, and explored its applications to time series analysis.
      - layout: top-left
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: BSc in mathematics; Minor in statistics
        sub_title: Cal Poly, San Luis Obispo
        caption: 2011 — 2016
        # quote: >
        #   " "
        description: | # this will include new lines to allow paragraphs
          Studied applied mathematics with a focus on computer science, with a minor in statistics.
  - title: Experience
    layout: list
    content:
      - layout: top-left
        title: Topological data analysis seminar organizer
        border: weak
        sub_title: University of Florida
        caption: Aug 2024 — Dec 2024
        link: https://tda.math.ufl.edu/fall24/
        # quote: >
        #   " "
        description: | # this will include new lines to allow paragraphs
          Organized and led a seminar on topological data analysis for graduate students at the University of Florida. The seminar covers recent advances in theory and applications of topological data analysis.

          During my time as seminar organizer, I shifted focus toward applications of TDA and algorithm design.
      - layout: top-left
        title: SLO Classical Academy
        border: weak
        sub_title: Algebra I teacher
        caption: 2020 — 2021
        link: https://sloclassical.org/
        # quote: >
        #   " "
        description: | # this will include new lines to allow paragraphs
          Taught Algebra I to high school and middle school students at a private school in San Luis Obispo, CA. These courses were hybrid in-person and online due to the COVID-19 pandemic. I created lesson plans, assignments, and assessments for the course.

          Was a member of a curriculum development team to adjust the curriculum to have a more gradual flow of concepts and ease the introduction to higher degree polynomials.
      - layout: top-left
        title: Graduate Teaching Assistant
        sub_title: Cal Poly, San Luis Obispo
        caption: 2018 — 2020
        # quote: >
        #   " "
        description: | # this will include new lines to allow paragraphs
          Instructor of Record for Precalculus (MATH 116, 3 courses; MATH 118, 1 course) and Business Calculus (MATH 221, 2 courses) courses.

          For these courses, I wrote syllabi, created and graded assignments and exams, held office hours, and taught lectures. During the Spring 2020 quarter, I adapted to online teaching for the COVID-19 pandemic and created online lectures and materials for students.
  - title: Publications and Presentations
    layout: text
    content: | # this will include new lines to allow paragraphs
      For a more in depth list of presentations and talks, please refer to my [CV](https://tuqpham0.github.io/assets/Tuyen_Pham_-_CV.pdf). You can find a general overview of my research projects [here](https://tuqpham0.github.io/research/).
      - ["Computing Representatives of Persistent Homology Generators with a Double Twist"](https://arxiv.org/abs/2403.04100)<br>
        P., Wagner
        - Published and presented at the 25th Canadian Conference on Computational Geometry (CCCG 2023).
      - ["Fast Kd-Trees for the Kullback—Leibler Divergence and Other Decomposable Bregman Divergences"](https://arxiv.org/abs/2502.13425)<br>
        P., Wagner
        - Published and presented at the 19th Algorithms and Data Structures Symposium (WADS 2025).
      - ["Bregman-Hausdorff divergence: strengthening the connections between computational geometry and machine learning"](https://arxiv.org/abs/2504.07322)<br>
        P., Dal Poz Kouřimskà, Wagner
        - Published in Machine Learning and Knowledge Extraction 2025.
  - title: More about me
    layout: text
    content: | # this will include new lines to allow paragraphs
          Outside of academia, I enjoy bouldering, lifting, drawing, and cooking.

          In addition to English, I am conversationally fluent in Vietnamese and Japanese, and am currently learning Spanish. 

# Footer
footer_show_references: true
references_title: References on request

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
